import { Code, Layers, BookOpen, Zap, ClipboardList } from "lucide-react"
import { Button } from "./ui/button";

export function HeroSection() {
  const quiz_url = "https://easy-quizz-nine.vercel.app?quiz=JTVCJTdCJTIyaSUyMiUzQTElMkMlMjJ0JTIyJTNBJTIybSUyMiUyQyUyMnElMjIlM0ElMjJJbiUyMGElMjBkb2N1bWVudC1vcmllbnRlZCUyME5vU1FMJTIwZGF0YWJhc2UlMjBsaWtlJTIwTW9uZ29EQiUyQyUyMHdoYXQlMjBpcyUyMHRoZSUyMGVxdWl2YWxlbnQlMjBvZiUyMGFuJTIwU1FMJTIwJ1RhYmxlJyUzRiUyMiUyQyUyMm8lMjIlM0ElNUIlMjJEb2N1bWVudCUyMiUyQyUyMkNvbGxlY3Rpb24lMjIlMkMlMjJGaWVsZCUyMiUyQyUyMkRhdGFiYXNlJTIyJTVEJTJDJTIyYyUyMiUzQSUyMkNvbGxlY3Rpb24lMjIlN0QlMkMlN0IlMjJpJTIyJTNBMiUyQyUyMnQlMjIlM0ElMjJtJTIyJTJDJTIycSUyMiUzQSUyMldoaWNoJTIwYmluYXJ5JTIwZm9ybWF0JTIwZG9lcyUyME1vbmdvREIlMjB1c2UlMjBpbnRlcm5hbGx5JTIwdG8lMjBzdG9yZSUyMGRhdGElMjBmb3IlMjBoaWdoZXIlMjBlZmZpY2llbmN5JTIwYW5kJTIwbW9yZSUyMGRhdGElMjB0eXBlcyUzRiUyMiUyQyUyMm8lMjIlM0ElNUIlMjJKU09OJTIyJTJDJTIyWE1MJTIyJTJDJTIyQlNPTiUyMiUyQyUyMllBTUwlMjIlNUQlMkMlMjJjJTIyJTNBJTIyQlNPTiUyMiU3RCUyQyU3QiUyMmklMjIlM0EzJTJDJTIydCUyMiUzQSUyMm0lMjIlMkMlMjJxJTIyJTNBJTIyV2hpY2glMjBmaWVsZCUyMGlzJTIwYXV0b21hdGljYWxseSUyMGFkZGVkJTIwdG8lMjBldmVyeSUyMGRvY3VtZW50JTIwYXMlMjBhJTIwdW5pcXVlJTIwcHJpbWFyeSUyMGtleSUyMGlmJTIwbm90JTIwZXhwbGljaXRseSUyMHByb3ZpZGVkJTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMmlkJTIyJTJDJTIyX2lkJTIyJTJDJTIya2V5JTIyJTJDJTIydXVpZCUyMiU1RCUyQyUyMmMlMjIlM0ElMjJfaWQlMjIlN0QlMkMlN0IlMjJpJTIyJTNBNCUyQyUyMnQlMjIlM0ElMjJiJTIyJTJDJTIycSUyMiUzQSUyMk5vU1FMJTIwZG9jdW1lbnQlMjBkYXRhYmFzZXMlMjBnZW5lcmFsbHklMjByZXF1aXJlJTIweW91JTIwdG8lMjBkZWZpbmUlMjBhJTIwZml4ZWQlMjBzY2hlbWElMjBiZWZvcmUlMjBpbnNlcnRpbmclMjBhbnklMjBkYXRhLiUyMiUyQyUyMm8lMjIlM0ElNUIlMjJUcnVlJTIyJTJDJTIyRmFsc2UlMjIlNUQlMkMlMjJjJTIyJTNBJTIyRmFsc2UlMjIlN0QlMkMlN0IlMjJpJTIyJTNBNSUyQyUyMnQlMjIlM0ElMjJtJTIyJTJDJTIycSUyMiUzQSUyMldoaWNoJTIwY29tbWFuZCUyMGlzJTIwdXNlZCUyMHRvJTIwaW5zZXJ0JTIwbXVsdGlwbGUlMjBkb2N1bWVudHMlMjBpbnRvJTIwYSUyMGNvbGxlY3Rpb24lMjBhdCUyMG9uY2UlM0YlMjIlMkMlMjJvJTIyJTNBJTVCJTIyZGIuY29sbGVjdGlvbi5hZGRNYW55KCklMjIlMkMlMjJkYi5jb2xsZWN0aW9uLmluc2VydE1hbnkoKSUyMiUyQyUyMmRiLmNvbGxlY3Rpb24uaW5zZXJ0QXJyYXkoKSUyMiUyQyUyMmRiLmNvbGxlY3Rpb24uc2F2ZU1hbnkoKSUyMiU1RCUyQyUyMmMlMjIlM0ElMjJkYi5jb2xsZWN0aW9uLmluc2VydE1hbnkoKSUyMiU3RCUyQyU3QiUyMmklMjIlM0E2JTJDJTIydCUyMiUzQSUyMm0lMjIlMkMlMjJxJTIyJTNBJTIyV2hlbiUyMHVwZGF0aW5nJTIwYSUyMGRvY3VtZW50JTJDJTIwd2hpY2glMjBvcGVyYXRvciUyMGlzJTIwc3BlY2lmaWNhbGx5JTIwdXNlZCUyMHRvJTIwbW9kaWZ5JTIwdGhlJTIwdmFsdWUlMjBvZiUyMGElMjBmaWVsZCUyMHdpdGhvdXQlMjByZXBsYWNpbmclMjB0aGUlMjB3aG9sZSUyMGRvY3VtZW50JTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMiUyNHNldCUyMiUyQyUyMiUyNG1vZGlmeSUyMiUyQyUyMiUyNHJlcGxhY2UlMjIlMkMlMjIlMjRjaGFuZ2UlMjIlNUQlMkMlMjJjJTIyJTNBJTIyJTI0c2V0JTIyJTdEJTJDJTdCJTIyaSUyMiUzQTclMkMlMjJ0JTIyJTNBJTIyYiUyMiUyQyUyMnElMjIlM0ElMjJJZiUyMHlvdSUyMHBlcmZvcm0lMjBhbiUyMHVwZGF0ZSUyMGNvbW1hbmQlMjB3aXRob3V0JTIwdXNpbmclMjB1cGRhdGUlMjBvcGVyYXRvcnMlMjAobGlrZSUyMCUyNHNldCklMkMlMjB0aGUlMjB1cGRhdGUlMjB3aWxsJTIwcmVwbGFjZSUyMHRoZSUyMGVudGlyZSUyMGRvY3VtZW50JTIwd2l0aCUyMHRoZSUyMG5ldyUyMGRhdGElMjBwcm92aWRlZC4lMjIlMkMlMjJvJTIyJTNBJTVCJTIyVHJ1ZSUyMiUyQyUyMkZhbHNlJTIyJTVEJTJDJTIyYyUyMiUzQSUyMlRydWUlMjIlN0QlMkMlN0IlMjJpJTIyJTNBOCUyQyUyMnQlMjIlM0ElMjJtJTIyJTJDJTIycSUyMiUzQSUyMldoaWNoJTIwcXVlcnklMjBvcGVyYXRvciUyMHNlbGVjdHMlMjBkb2N1bWVudHMlMjB3aGVyZSUyMGElMjBmaWVsZCdzJTIwdmFsdWUlMjBtYXRjaGVzJTIwYW55JTIwdmFsdWUlMjBzcGVjaWZpZWQlMjBpbiUyMGFuJTIwYXJyYXklMjAoZS5nLiUyQyUyMG1hdGNoaW5nJTIwJ0EnJTIwb3IlMjAnQicpJTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMiUyNGFuZCUyMiUyQyUyMiUyNGFsbCUyMiUyQyUyMiUyNGluJTIyJTJDJTIyJTI0b3IlMjIlNUQlMkMlMjJjJTIyJTNBJTIyJTI0aW4lMjIlN0QlMkMlN0IlMjJpJTIyJTNBOSUyQyUyMnQlMjIlM0ElMjJtJTIyJTJDJTIycSUyMiUzQSUyMldoaWNoJTIwc3ludGF4JTIwY29ycmVjdGx5JTIwZmlsdGVycyUyMGZvciUyMGRvY3VtZW50cyUyMHdoZXJlJTIwdGhlJTIwJ2FnZSclMjBmaWVsZCUyMGlzJTIwZ3JlYXRlciUyMHRoYW4lMjAyNSUzRiUyMiUyQyUyMm8lMjIlM0ElNUIlMjIlN0IlMjBhZ2UlM0ElMjAlN0IlMjAlMjRndCUzQSUyMDI1JTIwJTdEJTIwJTdEJTIyJTJDJTIyJTdCJTIwYWdlJTNBJTIwJTdCJTIwJTI0bHQlM0ElMjAyNSUyMCU3RCUyMCU3RCUyMiUyQyUyMiU3QiUyMGFnZSUzQSUyMCUzRSUyMDI1JTIwJTdEJTIyJTJDJTIyJTdCJTIwYWdlJTNBJTIwJTdCJTIwJTI0Z3RlJTNBJTIwMjUlMjAlN0QlMjAlN0QlMjIlNUQlMkMlMjJjJTIyJTNBJTIyJTdCJTIwYWdlJTNBJTIwJTdCJTIwJTI0Z3QlM0ElMjAyNSUyMCU3RCUyMCU3RCUyMiU3RCUyQyU3QiUyMmklMjIlM0ExMCUyQyUyMnQlMjIlM0ElMjJtJTIyJTJDJTIycSUyMiUzQSUyMldoaWNoJTIwb3BlcmF0b3IlMjBhbGxvd3MlMjB5b3UlMjB0byUyMG1hdGNoJTIwYW4lMjBhcnJheSUyMGVsZW1lbnQlMjB0aGF0JTIwc2F0aXNmaWVzJTIwbXVsdGlwbGUlMjBjcml0ZXJpYSUyMHNpbXVsdGFuZW91c2x5JTIwKGUuZy4lMkMlMjBwcmljZSUyMCUzRSUyMDEwMCUyMEFORCUyMGl0ZW0lMjAlM0QlMjAnYm9vayclMjB3aXRoaW4lMjB0aGUlMjBzYW1lJTIwb2JqZWN0KSUzRiUyMiUyQyUyMm8lMjIlM0ElNUIlMjIlMjRhbmQlMjIlMkMlMjIlMjRhbGwlMjIlMkMlMjIlMjR3aGVyZSUyMiUyQyUyMiUyNGVsZW1NYXRjaCUyMiU1RCUyQyUyMmMlMjIlM0ElMjIlMjRlbGVtTWF0Y2glMjIlN0QlMkMlN0IlMjJpJTIyJTNBMTElMkMlMjJ0JTIyJTNBJTIybSUyMiUyQyUyMnElMjIlM0ElMjJJbiUyMHRoZSUyMEFnZ3JlZ2F0aW9uJTIwUGlwZWxpbmUlMkMlMjB3aGljaCUyMHN0YWdlJTIwaXMlMjB1c2VkJTIwdG8lMjBmaWx0ZXIlMjBkb2N1bWVudHMlMjAoc2ltaWxhciUyMHRvJTIwdGhlJTIwU1FMJTIwV0hFUkUlMjBjbGF1c2UpJTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMiUyNHByb2plY3QlMjIlMkMlMjIlMjRtYXRjaCUyMiUyQyUyMiUyNGdyb3VwJTIyJTJDJTIyJTI0ZmlsdGVyJTIyJTVEJTJDJTIyYyUyMiUzQSUyMiUyNG1hdGNoJTIyJTdEJTJDJTdCJTIyaSUyMiUzQTEyJTJDJTIydCUyMiUzQSUyMm0lMjIlMkMlMjJxJTIyJTNBJTIyV2hhdCUyMGlzJTIwdGhlJTIwZnVuY3Rpb24lMjBvZiUyMHRoZSUyMCUyNHVud2luZCUyMHN0YWdlJTIwaW4lMjBhbiUyMGFnZ3JlZ2F0aW9uJTIwcGlwZWxpbmUlM0YlMjIlMkMlMjJvJTIyJTNBJTVCJTIySXQlMjBzb3J0cyUyMHRoZSUyMGRvY3VtZW50cyUyMGluJTIwcmV2ZXJzZSUyMG9yZGVyLiUyMiUyQyUyMkl0JTIwZ3JvdXBzJTIwZG9jdW1lbnRzJTIwYnklMjBhJTIwc3BlY2lmaWMlMjBmaWVsZC4lMjIlMkMlMjJJdCUyMGRlY29uc3RydWN0cyUyMGFuJTIwYXJyYXklMjBmaWVsZCUyMGZyb20lMjBhJTIwZG9jdW1lbnQlMjB0byUyMG91dHB1dCUyMGElMjBkb2N1bWVudCUyMGZvciUyMGVhY2glMjBlbGVtZW50LiUyMiUyQyUyMkl0JTIwcmVtb3ZlcyUyMGR1cGxpY2F0ZXMlMjBmcm9tJTIwYW4lMjBhcnJheS4lMjIlNUQlMkMlMjJjJTIyJTNBJTIySXQlMjBkZWNvbnN0cnVjdHMlMjBhbiUyMGFycmF5JTIwZmllbGQlMjBmcm9tJTIwYSUyMGRvY3VtZW50JTIwdG8lMjBvdXRwdXQlMjBhJTIwZG9jdW1lbnQlMjBmb3IlMjBlYWNoJTIwZWxlbWVudC4lMjIlN0QlMkMlN0IlMjJpJTIyJTNBMTMlMkMlMjJ0JTIyJTNBJTIybSUyMiUyQyUyMnElMjIlM0ElMjJXaGljaCUyMGFjY3VtdWxhdG9yJTIwb3BlcmF0b3IlMjBpcyUyMHVzZWQlMjB3aXRoaW4lMjB0aGUlMjAlMjRncm91cCUyMHN0YWdlJTIwdG8lMjBjYWxjdWxhdGUlMjB0aGUlMjB0b3RhbCUyMHN1bSUyMG9mJTIwYSUyMG51bWVyaWNhbCUyMGZpZWxkJTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMiUyNGFkZCUyMiUyQyUyMiUyNHRvdGFsJTIyJTJDJTIyJTI0c3VtJTIyJTJDJTIyJTI0Y291bnQlMjIlNUQlMkMlMjJjJTIyJTNBJTIyJTI0c3VtJTIyJTdEJTJDJTdCJTIyaSUyMiUzQTE0JTJDJTIydCUyMiUzQSUyMm0lMjIlMkMlMjJxJTIyJTNBJTIyV2hpY2glMjBhZ2dyZWdhdGlvbiUyMHN0YWdlJTIwYWxsb3dzJTIweW91JTIwdG8lMjBwZXJmb3JtJTIwYSUyMCdMZWZ0JTIwT3V0ZXIlMjBKb2luJyUyMHdpdGglMjBhbm90aGVyJTIwY29sbGVjdGlvbiUyMGluJTIwdGhlJTIwc2FtZSUyMGRhdGFiYXNlJTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMiUyNGpvaW4lMjIlMkMlMjIlMjRsb29rdXAlMjIlMkMlMjIlMjRjb25uZWN0JTIyJTJDJTIyJTI0bWVyZ2UlMjIlNUQlMkMlMjJjJTIyJTNBJTIyJTI0bG9va3VwJTIyJTdEJTJDJTdCJTIyaSUyMiUzQTE1JTJDJTIydCUyMiUzQSUyMm0lMjIlMkMlMjJxJTIyJTNBJTIyV2hlbiUyMHNvcnRpbmclMjByZXN1bHRzJTIwdXNpbmclMjAuc29ydCgpJTJDJTIwd2hpY2glMjB2YWx1ZSUyMHJlcHJlc2VudHMlMjBhJTIwZGVzY2VuZGluZyUyMG9yZGVyJTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMjElMjIlMkMlMjIwJTIyJTJDJTIyLTElMjIlMkMlMjJERVNDJTIyJTVEJTJDJTIyYyUyMiUzQSUyMi0xJTIyJTdEJTJDJTdCJTIyaSUyMiUzQTE2JTJDJTIydCUyMiUzQSUyMmIlMjIlMkMlMjJxJTIyJTNBJTIyQ3JlYXRpbmclMjBpbmRleGVzJTIwZ2VuZXJhbGx5JTIwaW1wcm92ZXMlMjB0aGUlMjBzcGVlZCUyMG9mJTIwcmVhZCUyMG9wZXJhdGlvbnMlMjAoZmluZGluZyUyMGRhdGEpJTIwYnV0JTIwY2FuJTIwc2xpZ2h0bHklMjBzbG93JTIwZG93biUyMHdyaXRlJTIwb3BlcmF0aW9ucyUyMChpbnNlcnRzJTJGdXBkYXRlcykuJTIyJTJDJTIybyUyMiUzQSU1QiUyMlRydWUlMjIlMkMlMjJGYWxzZSUyMiU1RCUyQyUyMmMlMjIlM0ElMjJUcnVlJTIyJTdEJTJDJTdCJTIyaSUyMiUzQTE3JTJDJTIydCUyMiUzQSUyMm0lMjIlMkMlMjJxJTIyJTNBJTIySG93JTIwZG8lMjB5b3UlMjBleHBsaWNpdGx5JTIwZXhjbHVkZSUyMHRoZSUyMGRlZmF1bHQlMjAnX2lkJyUyMGZpZWxkJTIwZnJvbSUyMHRoZSUyMHJlc3VsdHMlMjBvZiUyMGElMjBxdWVyeSUyMHVzaW5nJTIwcHJvamVjdGlvbiUzRiUyMiUyQyUyMm8lMjIlM0ElNUIlMjIlN0IlMjBfaWQlM0ElMjBmYWxzZSUyMCU3RCUyMiUyQyUyMiU3QiUyMF9pZCUzQSUyMDAlMjAlN0QlMjIlMkMlMjIlN0IlMjBfaWQlM0ElMjAtMSUyMCU3RCUyMiUyQyUyMiU3QiUyMGV4Y2x1ZGUlM0ElMjAnX2lkJyUyMCU3RCUyMiU1RCUyQyUyMmMlMjIlM0ElMjIlN0IlMjBfaWQlM0ElMjAwJTIwJTdEJTIyJTdEJTJDJTdCJTIyaSUyMiUzQTE4JTJDJTIydCUyMiUzQSUyMm0lMjIlMkMlMjJxJTIyJTNBJTIyV2hpY2glMjBvZiUyMHRoZSUyMGZvbGxvd2luZyUyMGRhdGElMjB0eXBlcyUyMGlzJTIwc3VwcG9ydGVkJTIwbmF0aXZlbHklMjBpbiUyMEJTT04lMjBidXQlMjBpcyUyME5PVCUyMGElMjBzdGFuZGFyZCUyMEpTT04lMjBkYXRhJTIwdHlwZSUzRiUyMiUyQyUyMm8lMjIlM0ElNUIlMjJTdHJpbmclMjIlMkMlMjJCb29sZWFuJTIyJTJDJTIyRGF0ZSUyMiUyQyUyMkFycmF5JTIyJTVEJTJDJTIyYyUyMiUzQSUyMkRhdGUlMjIlN0QlMkMlN0IlMjJpJTIyJTNBMTklMkMlMjJ0JTIyJTNBJTIybSUyMiUyQyUyMnElMjIlM0ElMjJXaGljaCUyMG9wZXJhdG9yJTIwaXMlMjB1c2VkJTIwdG8lMjBwZXJmb3JtJTIwcGF0dGVybiUyMG1hdGNoaW5nJTIwKGxpa2UlMjBzZWFyY2hpbmclMjBmb3IlMjB0ZXh0JTIwdGhhdCUyMHN0YXJ0cyUyMHdpdGglMjBhJTIwc3BlY2lmaWMlMjBsZXR0ZXIpJTNGJTIyJTJDJTIybyUyMiUzQSU1QiUyMiUyNHRleHQlMjIlMkMlMjIlMjRsaWtlJTIyJTJDJTIyJTI0cmVnZXglMjIlMkMlMjIlMjRzZWFyY2glMjIlNUQlMkMlMjJjJTIyJTNBJTIyJTI0cmVnZXglMjIlN0QlMkMlN0IlMjJpJTIyJTNBMjAlMkMlMjJ0JTIyJTNBJTIyYiUyMiUyQyUyMnElMjIlM0ElMjJJbiUyMGElMjBzaW5nbGUlMjBNb25nb0RCJTIwY29sbGVjdGlvbiUyQyUyMGl0JTIwaXMlMjBwb3NzaWJsZSUyMHRvJTIwaGF2ZSUyMGRvY3VtZW50cyUyMHRoYXQlMjBoYXZlJTIwZGlmZmVyZW50JTIwc3RydWN0dXJlcyUyMChpLmUuJTJDJTIwZGlmZmVyZW50JTIwc2V0cyUyMG9mJTIwZmllbGRzKS4lMjIlMkMlMjJvJTIyJTNBJTVCJTIyVHJ1ZSUyMiUyQyUyMkZhbHNlJTIyJTVEJTJDJTIyYyUyMiUzQSUyMlRydWUlMjIlN0QlNUQ=";
  return (
    <header className="pt-24 sm:pt-32 pb-16 sm:pb-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center">
    
      <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight mb-6 text-balance">
        Ace Your{" "}
        <span className="bg-gradient-to-r from-blue-400 to-emerald-400 bg-clip-text text-transparent">NoSQL Exam</span>
      </h1>
      <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 text-pretty">
        A comprehensive, interactive cheat sheet for Document-Oriented Databases. Toggle{" "}
        <strong className="text-foreground">Study Mode</strong> to quiz yourself on key definitions.
      </p>
      <div className="flex flex-col sm:flex-row justify-center gap-4">
        <a
          href="#crud"
          className="inline-flex items-center justify-center bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold transition"
        >
          <Code className="w-5 h-5 mr-2" /> Cheat Sheet
        </a>
        <a
          href="#aggregation"
          className="inline-flex items-center justify-center bg-secondary hover:bg-secondary/80 text-secondary-foreground px-6 py-3 rounded-lg font-semibold transition"
        >
          <Layers className="w-5 h-5 mr-2" /> Pipelines
        </a>
         <Button
              size="lg"
              variant="outline"
              className="inline-flex items-center justify-center bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg font-semibold transition h-[48px]"
              asChild
            >
              <a href={quiz_url} target="_blank" rel="noopener noreferrer">
                <ClipboardList className="w-5 h-5 mr-2" />
                Take a Quiz
              </a>
            </Button>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-16 max-w-3xl mx-auto">
        {[
          { icon: BookOpen, label: "Topics", value: "7+" },
          { icon: Code, label: "Code Examples", value: "50+" },
          { icon: Layers, label: "Pipeline Stages", value: "8" },
          { icon: Zap, label: "Quiz Questions", value: "30+" },
        ].map((stat) => (
          <div key={stat.label} className="bg-card border border-border rounded-xl p-4">
            <stat.icon className="h-5 w-5 text-blue-400 mx-auto mb-2" />
            <div className="text-2xl font-bold">{stat.value}</div>
            <div className="text-xs text-muted-foreground">{stat.label}</div>
          </div>
        ))}
      </div>
    </header>
  )
}
